version: '2'

services:
    node:
        build: network/
        image: substrate/network
        expose:
            - "3000"
        volumes:
            - connection_data:/network/chain/tmp
    sms:
        build: sms/
        image: substrate/sms
        expose:
            - "5000"
        
volumes:
    connection_data:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: "size=10m"

